[package]
name = "worp-playground"
version = "0.1.0"
authors = ["Joshua Rodgers <bytemr@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
worp-dice = { git = "https://github.com/mr-byte/worp" }
worp-scroll = { git = "https://github.com/mr-byte/worp" }
