[package]
name = "worp-playground"
version = "0.1.0"
authors = ["Joshua Rodgers <bytemr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"

worp-dice = { git = "https://github.com/mr-byte/worp" }
worp-scroll = { git = "https://github.com/mr-byte/worp" }